name = "snowmanbot-api"
main = "worker.js"
compatibility_date = "2026-03-28"
workers_dev = true

[assets]
directory = "./frontend"
binding = "ASSETS"
run_worker_first = true

[[d1_databases]]
binding = "DB"
database_name = "<user_data>"
database_id = "<8ede3654-b27d-4648-9eb6-163cb803df73>"

[vars]
ADMIN_CHANNEL_ID = "-1003718907769"
