name = "snowmanbot-api"
main = "worker.js"
compatibility_date = "2026-03-27"

[env.production]
kv_namespaces = [
  { binding = "USER_DATA", id = "a6f263a398c0452bb245f903b77656ff" }
]

[vars]
# BOT_TOKEN will be read from Cloudflare Secrets
